version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automated
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: scope
